### ISSUE TITLE
The .js part of your module namespace might be problematic

### ISSUE THREAD

**Issue by camfindlay** [axllent/silverstripe-analytics-js#4]
Hey, just came across your module, very useful for the newer universal analytics however I have found that when you module is listed on the addons website the .js part causes some problems as I beleive it gets interpreted as a javascript file rather than a listing on the addons site.

Might pay to revise this and resubmit to packagist with a more meaningful name (perhaps include an indication that it is the universal tracking). For example: axllent/silverstripe-universalanalytics or something to that effect.

**Comment by axllent** [comment]
I've renamed the project as it seemed like the SilverStripe addons site isn't going to deal with the extension issue ;-)
